# Generated by Django 4.2.6 on 2023-10-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sebo', '0002_alter_disco_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disco',
            name='ano',
            field=models.IntegerField(),
        ),
    ]
